name: Build and Deploy (tag-based GitOps)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      id-token: write

    steps:
      # Checkout TAG (źródło kodu aplikacji)
      - name: Checkout application source (tag)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          IMAGE_VERSION="${TAG_NAME#v}"
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

      # Auth GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/364308840078/locations/global/workloadIdentityPools/github-actions/providers/github-provider
          service_account: github-ci@gke-autopilot-gitops-starter.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      # Build & push image
      - name: Build Docker image
        run: |
          docker build \
            -t europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION} \
            ./app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${{ env.IMAGE_VERSION }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION}

      # Checkout deploy/app (GitOps state)
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy/app
          fetch-depth: 0

      # Update manifest
      - name: Update image tag in deployment.yml
        run: |
          sed -i \
            "s|image: .*fastapi-app:.*|image: europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION}|" \
            k8s/deployment.yml

      # Commit & push (TO JEST KLUCZ)
      - name: Commit GitOps change
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s/deployment.yml
          git commit -m "chore(deploy): release v${IMAGE_VERSION}"
          git push origin deploy/app
