name: Build and Push Docker Image (on tag)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy/app
          fetch-depth: 0

      - name: Extract version from git tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          IMAGE_VERSION="${TAG_NAME#v}"
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/364308840078/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: github-ci@gke-autopilot-gitops-starter.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION} ./app

      - name: Push docker image
        run: |
          docker push europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION}

      - name: Update image tag in deployment.yml
        run: |
          sed -i \
          "s|europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:.*|europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app:${IMAGE_VERSION}|" \
          k8s/deployment.yml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s/deployment.yml
          git commit -m "chore: deploy v${IMAGE_VERSION}"
          git push origin deploy/app
