name: Build and Push Docker Image (on tag)

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/364308840078/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: github-ci@gke-autopilot-gitops-starter.iam.gserviceaccount.com
        
      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Extract version from git tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          IMAGE_VERSION="$TAG_NAME#v"
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
        
      - name: Build docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app${IMAGE_VERSION} \
          ./app
      
      - name: Push docker Image 
        run: |
          docker push europe-west1-docker.pkg.dev/gke-autopilot-gitops-starter/app-repo/fastapi-app${IMAGE_VERSION}




          